modLoader="javafml"
loaderVersion="[40,)"
license="LGPLv3.0"

issueTrackerURL="https://github.com/62832/AppliedComputing/issues"
displayURL="https://github.com/62832/AppliedComputing"

[[mods]]
modId="appcom"
version="${version}"
displayName="Applied Computing"
credits=""
authors="90"
description="Computer networking via ME networking."

[[dependencies.appcom]]
    modId="ae2"
    mandatory=true
    versionRange = "(,12.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.appcom]]
    modId="computercraft"
    mandatory=true
    versionRange = "[1.100,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.appcom]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.appcom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
